version: "3.7"
services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www/html
      - ./volumes/php.ini:/usr/local/etc/php/php.ini
